### ISSUE TITLE
Refine rerank code to fix bug: TypeError: 'numpy.float32' object is not iterable

### ISSUE THREAD

**Issue by lllilithyang** [thinkany-ai/rag-search#10]
I set 'is_reranking' to true in .env and meet error: TypeError: 'numpy.float32' object is not iterable
It seems that the type of 'score' in flashrank output is 'numpy.float32' and fastapi fail to process this type. 
I hard code it to type float in following position and it fixed. I think you can modify the code to make it more robust, or do you have any concern to use type 'numpy.float32' here?
![image](https://github.com/user-attachments/assets/5e80c252-749f-45ff-9431-a0b0dba2ce23)

**Comment by wangr0031** [comment]
这是因为search_results里面的score值不符合python的float类型，需要做下转换
