### ISSUE TITLE
能否提供下zilliz中collection的Schema，谢谢！

### ISSUE THREAD

**Issue by NBchitu** [thinkany-ai/rag-search#4]

**Comment by WendaoLee** [comment]
这个 demo 里的 Schema 就是最基本的 Schema，字段中一个是主键id，一个是向量化字段 embedding。剩余的字段是动态字段。

**Comment by NBchitu** [comment]
> 这个 demo 里的 Schema 就是最基本的 Schema，字段中一个是主键id，一个是向量化字段 embedding。剩余的字段是动态字段。

感谢！

**Comment by NBchitu** [comment]
![Schema](https://github.com/thinkany-ai/rag-search/assets/7865296/6cdae0e8-c534-4b6e-a892-6a603d8d00d8)
可以了
